In [2]:
import numpy as np

# 1 - Indexing

In [4]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a[0, 1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a[0:1, 1:3]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [12]:
a[..., -1]

array([[ 3,  7, 11],
       [15, 19, 23]])

# 2 - Operations on arrays

In [18]:
b = np.arange(100, 112).reshape(2,3,2)

In [19]:
b

array([[[100, 101],
        [102, 103],
        [104, 105]],

       [[106, 107],
        [108, 109],
        [110, 111]]])

In [21]:
np.concatenate([a,b], axis = 2)

array([[[  0,   1,   2,   3, 100, 101],
        [  4,   5,   6,   7, 102, 103],
        [  8,   9,  10,  11, 104, 105]],

       [[ 12,  13,  14,  15, 106, 107],
        [ 16,  17,  18,  19, 108, 109],
        [ 20,  21,  22,  23, 110, 111]]])